spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_backend?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
    username: root
    password:

cors:
  allowedOrigins: "*"

server:
  port: 80