spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_backend?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Jakarta

app:
  jwtSecret: secretKey
  jwtExpirationInMs: 21600000
  profile: "development"

cors:
  allowedOrigins: "*"

server:
  port: 8080