spring:
  config:
    import: file:./app-config.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Jakarta

app:
  jwtSecret: ecretKey
  jwtExpirationInMs: 21600000
  profile: "development"